### ISSUE TITLE
Revise histogram of chips sold to show proportions

### ISSUE THREAD

**Issue by snairdesai** [snairdesai/sameer_template#1]
See task description [here](https://github.com/gslab-econ/ra-manual/wiki/Practice-Task). The goal is to revise the histogram in [`/data/output/chips_sold.pdf`](https://github.com/snairdesai/sameer_template/blob/main/data/output/chips_sold.pdf) to display percentage values on the y-axis, rather than counts. The relevant code to check here is in [`/data/code/clean_data.py`](https://github.com/snairdesai/sameer_template/blob/issue1_prop_hist/data/code/clean_data.py).

**Comment by anacarolinapq** [comment]
@snairdesai per [here](https://github.com/gslab-econ/lab-manual/wiki/Issues#deliverable), you should add a summary with deliverables and close the issue. This is usually done right before we open a PR, and all future comments are made on the PR itself / we update the summary comment if needed. Could you add the summary here and in #3 and close? Thanks!

**Comment by anacarolinapq** [comment]
@snairdesai also, I noticed that the Practice Task description on the manual is not aligned with that the rest of the manual says re: summary/deliverables, so I will change that.

**Comment by snairdesai** [comment]
### Summary + Deliverable

----

In this issue (#1), I completed the first step in the `gslab-econ/lab-manual` [Practice Task](https://github.com/gslab-econ/lab-manual/wiki/Practice-Task). I revised the histogram in `/data/output/chips_sold.pdf` to display percentage values on the y-axis, rather than counts. The relevant code which integrated these changes is in `/data/code/clean_data.py`. The revised histogram can be found in `/paper_slides/output/paper.pdf`. All changes were made in [`47bc5ac`](https://github.com/snairdesai/sameer_template/commit/47bc5acce03ae00fad4457e9d01f3217e124d3db), and a PR (#2) was issued to merge to `master` with @anacarolinapq as a reviewer.

**Comment by snairdesai** [comment]
### Summary + Deliverable

----

In this issue (#1), I completed the first step in the `gslab-econ/lab-manual` [Practice Task](https://github.com/gslab-econ/lab-manual/wiki/Practice-Task). I revised the histogram in `/data/output/chips_sold.pdf` to display percentage values on the y-axis, rather than counts. The relevant code which integrated these changes is in `/data/code/clean_data.py`. The revised histogram can be found in `/paper_slides/output/paper.pdf`. All changes were made in [`47bc5ac`](https://github.com/snairdesai/sameer_template/commit/47bc5acce03ae00fad4457e9d01f3217e124d3db), and a PR (#2) was issued to merge to `master` with @anacarolinapq as a reviewer.
